### PR TITLE
add games controller, routes for new, create, show, destroy, add colu…

### PR DESCRIPTION
**Pull request by unyon**
Add Games controller
Add routes for Games new, create, show, destroy
add white_player_id, black_table_id, turn_player_id, status columns to Games table
add show page for games
add new page for games - added new form: 
current_user = white_player_id, 
black_player_id is a drop down select menu of all users not including current_user
add some users to the seeds.rb file
made minor edits to nav menu on application.html

### CODE REVIEW

**Comment by Shawydu** [comment]
Awesome code. But only one problem to me, when create a game, the creator will be write player with his game open for others join, rather than preselect the black player

**Comment by unyon** [comment]
In this case , the white player creates the game and selects the user who is the opponent.  
Would we just leave the field blank for others to join later?

**Comment by emilymay42** [comment]
It makes sense to have the option to select an opponent, but I think we should also have the option to begin a game without an opponent, and to join a pre-existing game. If we set the black_player_id to nil, then on the home page, we could list all available games by cycling through all games, but only listing those who's black_player_id is set to nil. Then, when a different user joins a game as the black player, the field will be overwritten with that user's id and the game removed from the list of available games.

**Comment by Shawydu** [comment]
I think for now get rid of form field for black player at new.html.erb page, we will do the logic as Emily says in some future cards.

**Comment by unyon** [comment]
ok I removed that from the new form

**Pull request merged**
