### PR TITLE
logic for player turns

### PR DESCRIPTION
**Pull request by unyon**
This is to alternate turns between the two players.
1) sets turn_player_id initially to white_player_id
2) only allows player whose id matches turn_player_id to make a move
3) only allows players to move their own piece
4)updates turn_player_id to next player after each move

### CODE REVIEW

**Comment by emilymay42** [comment]
Looks great-- using after_save was a really smart idea! Would you mind explaining the changes you made in user.rb and how the moves table will be used? Also, I think you forgot to delete a couple lines at the bottom of the pieces controller. Solid work, Mike! :+1:

**Comment by Shawydu** [comment]
Looks really awesome! except some code which shows tracks of your work should be removed to make code dry. Nice job!

**Comment by unyon** [comment]
For User.rb, I was need to check current_user for a method on the Piece model, which I guess you can't do.  So the code on User.rb, and the application controller is just so I can check the 'User.current.id' in the 'moving_own_piece' method.
The moves table Mike and I created when we were redoing the board.  I don't think we'll be using it so I'll delete it and clean up my other code.

**Comment by emilymay42** [comment]
I think it looks good!

**Pull request merged**
