### PR TITLE
make piece draggable and droppable

### PR DESCRIPTION
**Pull request by Shawydu**
Implement drag & drop on both move and capture on current phase.

Animation when pieces dropped on tile is a little weird, need to be improved somehow.

### CODE REVIEW

**Comment by emilymay42** [comment]
I think it looks good, but I'm not the most experienced in Javascript. How does that capture logic interact with the capture logic in the pieces controller?

**Comment by Shawydu** [comment]
@emilymay42 you may notice on line 65 to 68, when there is one piece on target tile to be dropped, that piece be replaced by dragged piece

**Comment by emilymay42** [comment]
Right, no, I saw that. I meant, currently in the pieces controller, there is code to delete a captured piece, and based on your PR, you didn't change that. I was just wondering if you needed to add the javascript code handling a capture (in addition to the deletion in the controller) because of the way drag-and-drop works? Because right now, when a piece is captured without the drag-and-drop, it just gets deleted and disappears. Does that make sense?

**Comment by Shawydu** [comment]
@emilymay42 yep, I didn't change the logic. In terms of Ajax, it's same with the previous one

**Pull request merged**
