### PR TITLE
add knight valid move

### PR DESCRIPTION
**Pull request by Shawydu**

### CODE REVIEW

**Comment by emilymay42** [comment]
Nice way to solve this! One thing- should it be if x < 3 && y < 3 instead of or? Because the change in x or y shouldn't be >3 in any case, from what I can tell, and if abs_x = 3 and abs_y = 0, then it would return true, but that's not a legal move.

**Comment by Shawydu** [comment]
@emilymay42 exactly! Appreciate your help

**Comment by unyon** [comment]
Should it be this because its L shape?
if abs_x == 2 && abs_y == 1 || abs_x == 1 && abs_y == 2

**Comment by Shawydu** [comment]
@unyon both should work well. your method is straightforward, like it

**Pull request merged**
