### PR TITLE
Add logic for is_obstructed

### PR DESCRIPTION
**Pull request by emilymay42**
This code will not return true if the destination square is occupied by an enemy piece. This means that, until capture logic is implemented, moving a piece onto an enemy piece is not advisable. When I did it, it made my piece straight up disappear. No idea why. But I think the rest of it should work!

### CODE REVIEW

**Comment by unyon** [comment]
It works.

**Comment by Shawydu** [comment]
This method works. The reason selected piece disappeared is because the selected piece append to the tile div where enemy's piece locate at, when moving selected piece onto it. So you could notice that the disappeared piece still exists when you inspect element on browser. And they both have the same x&y positions.
Also our click event is fired for selecting tile rather than piece. So when you continue moving the piece where last piece disappeared at, this code `prevpiece = $("#"+x+"-"+y+" img")` select both pieces and move them at same time.

**Comment by emilymay42** [comment]
Great catch, Shawy! That's a really clear explanation.

**Comment by emilymay42** [comment]
Looks really good, but shouldn't the captured logic come after the tests for is_obstructed and is_valid? And I think we need to add a line that only tests is_obstructed if piece.type != knight. Thanks for helping out with this!

**Comment by mikestonecodes** [comment]
Yep you're right :)

**Comment by emilymay42** [comment]
The captured logic in piece.rb still needs to be below is_obstructed, because the piece won't be captured if the move can't be executed. Otherwise it looks good!

**Pull request merged**
